name: Update Balance

on:
  workflow_dispatch:
    inputs:
      hwid:
        description: 'HWID игрока'
        required: true
      balance:
        description: 'Новый баланс'
        required: true

jobs:
  update-balance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update balance file
        run: |
          HWID="${{ github.event.inputs.hwid }}"
          BALANCE="${{ github.event.inputs.balance }}"
          FILE="balances/${HWID}.json"
          echo "{ \"balance\": ${BALANCE} }" > $FILE

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add balances/${{ github.event.inputs.hwid }}.json
          git commit -m "Update balance for ${{ github.event.inputs.hwid }}"
          git push
